### ISSUE TITLE
Percent sign should not be interpreted specially when inside a string literal

### ISSUE THREAD

**Issue by iafisher** [cronie-crond/cronie#195] opened 2024-12-08 14:42 UTC
This crontab line does not work:

```
*/1 * * * * date "+%H:%M" >> ~/date.log
```

According to crontab(5):

> A '%'  character in the command, unless escaped with a backslash (`\`), will be changed into newline characters, and all data after the first % will be sent to the command as standard input.

But it's hard to imagine that anyone would want a percent sign inside a string literal to be interpreted like this, because the resulting shell command is almost guaranteed to be malformed.

**Comment by t8m** [comment] 2024-12-09 08:32
The problem is that I cannot add full shell command line interpretation into crond. If I'd make `""` work, then next ask would be for `''` then for `$()` and so on. So closing as wontfix.

**Closed by t8m** 2024-12-09 08:32 UTC
Labels: enhancement, wontfix
